build:dotnetcore:
  image: mcr.microsoft.com/dotnet/core/sdk:5.0
  script:
    - dotnet --info
    - dotnet restore --verbosity detailed
    - dotnet build --verbosity detailed

test:dotnetcore:
   image: mcr.microsoft.com/dotnet/core/sdk:5.0
   script:
     - dotnet --info
     - dotnet restore --verbosity detailed
     - dotnet test --verbosity detailed
